### ISSUE TITLE
dnopt

### ISSUE THREAD

**Issue by pollinico** [snopt/snopt-python#13]
>>> import snopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicolo/miniconda3/envs/pyOpt-env/lib/python3.8/site-packages/snopt/__init__.py", line 8, in <module>
    from .solvers  import(
ImportError: cannot import name 'dnopt' from 'snopt.solvers' (/Users/nicolo/miniconda3/envs/pyOpt-env/lib/python3.8/site-packages/snopt/solvers/__init__.py)

**Comment by alberthli** [comment]
Use the `snopt-only` branch (see [this issue](https://github.com/snopt/snopt-python/issues/8#issuecomment-422469204)).
