### ISSUE TITLE
cannot run examples [libsnopt7.so.0: cannot open shared object file: No such file or directory]

### ISSUE THREAD

**Issue by HuaweiWang** [snopt/snopt-python#5]
Hi,

Thanks for developing this python interface for snopt. 

similar to issue #4, I experienced similar problems when installing snopt-python with precompiled snopt7, which I solve that by copy the built lib folder into the "snopt-python/solvers/'. The build and install snopt-python seems good.
```
Appending optimize.solvers configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers')
Appending optimize.solvers/snopt configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers/snopt')
Appending optimize.solvers/dnopt configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers/dnopt')
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "optimize.solvers.snopt7_python" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/solvers/f2py/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/solvers/f2py' to include_dirs.
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
running install_lib
copying build/lib.linux-x86_64-2.7/optimize/solvers/libsnopt7.so.0 -> /home/huawei/.local/lib/python2.7/site-packages/optimize/solvers
copying build/lib.linux-x86_64-2.7/optimize/solvers/libsnopt7.so.0.0.0 -> /home/huawei/.local/lib/python2.7/site-packages/optimize/solvers
copying build/lib.linux-x86_64-2.7/optimize/solvers/setup.py -> /home/huawei/.local/lib/python2.7/site-packages/optimize/solvers
byte-compiling /home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/setup.py to setup.pyc
running install_data
running install_egg_info
Removing /home/huawei/.local/lib/python2.7/site-packages/optimizeoptimize-0.0.0-py2.7.egg-info
Writing /home/huawei/.local/lib/python2.7/site-packages/optimizeoptimize-0.0.0-py2.7.egg-info
running install_clib
customize UnixCCompiler
```

However, I have an issue when running example (dieta.py). The error information always like following:

```
Traceback (most recent call last):
  File "dieta.py", line 7, in <module>
    from   optimize import snopta, SNOPT_options
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/__init__.py", line 8, in <module>
    from .solvers  import(
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/__init__.py", line 8, in <module>
    from .snopt    import snopta, snoptb, snoptc, sqopt
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/snopt/__init__.py", line 4, in <module>
    from .snopt import snopta, snoptb, snoptc, sqopt
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/snopt/snopt.py", line 4, in <module>
    from   optimize.solvers          import snopt7_python as fsnopt
ImportError: libsnopt7.so.0: cannot open shared object file: No such file or directory
```
Do you have suggestions what is wrong with this? Is it because my snopt didn't complied sucessfully (I did the make check with the the snopt only, it runs successfully)? Does the error means the connect between my complied snopt7 and snopt-python interface didn't connect with each other?

Thanks for the help!

**Comment by gnowzil** [comment]
I just looked into this on my linux machine.  Assuming everything else is fine, you have to add the location of the SNOPT Fortran library to LD_LIBRARY_PATH.  Will add it to the instructions.

**Comment by HuaweiWang** [comment]
Hi,
Thanks for the help. I added the LD_LIBRARY_PATH, and it works. Now the old issue removed, however, another error showed up:

```
huawei@huawei-HP-EliteBook-2570p:~/snopt-python-snopt-only/examples$ python dieta.py
Traceback (most recent call last):
  File "dieta.py", line 7, in <module>
    from   optimize import snopta, SNOPT_options
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/__init__.py", line 6, in <module>
    from .solvers  import(
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/__init__.py", line 6, in <module>
    from .snopt    import snopta, snoptb, snoptc, sqopt
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/snopt/__init__.py", line 4, in <module>
    from .snopt import snopta, snoptb, snoptc, sqopt
  File "/home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/snopt/snopt.py", line 4, in <module>
    from   optimize.solvers          import snopt7_python as fsnopt
ImportError: /home/huawei/.local/lib/python2.7/site-packages/optimize/solvers/snopt7_python.so: undefined symbol: snfileclose_
```
It seems the solver can find _snopt7_python.so_, but a small bug is inside the snopt7_python.so. Could you give me some suggestions on how to fix this? Thanks a lot!

**Comment by gnowzil** [comment]
snfileclose is a subroutine in the Fortran SNOPT library.  Assuming the python interface is picking up the library correctly, I'm not sure what's wrong.  Can you check if snfileclose is in the SNOPT library that you have?  You can use command 'nm' to list subroutines, etc in a library.

(Also, I've created an "snopt-only" branch that you should switch to if you haven't already)

**Comment by HuaweiWang** [comment]
Sorry to reply you late, I was in  conference last week. Here is my situation right now.

I am using the 'snopt-only' branch. I checked the SNOPT library, but there is no snfileclose library. The Snopt version I used is Version 7.4-1.1. Which Version do you use? Could you also check whether your SNOPT library has the snfileclose library or not? Thanks a lot!
